### ISSUE TITLE
When browsing for disk images (TNFS, SD), indicate when an image is already mounted in a drive slot

### ISSUE THREAD

**Issue by billkendrick** [FujiNetWIFI/fujinet-config-old#20]
# Purpose
If a disk image is already mounted on a drive slot, indicate which drive (and if it's read-only or read-write) within the "Disk Images" browser within CONFIG.

# Example
Right now, I see:
```
DISK IMAGES

/networking/

  ...
  Flickerterm.atr
  modem-programs.atr
  Platoterm.atr
  ...
```

I'm suggesting something like:
```
DISK IMAGES

/networking/

   ...
   Flickerterm.atr
1R modem-programs.atr
   Platoterm.atr
   ...
```

# Motivation
I frequently go on auto-pilot and begin navigating to a TNFS server to find a disk image I want to mount, only to realize I had already mounted it, once the drive slot selection comes up.

This would also have the side effect of being a 'confirmation' that the disk image was mounted, after a successful mount. (Currently, the user is left at the "Disk Images" list, which may confuse new users.)

# Note
I'm not sure how to indicate when a single disk image is simultaneously mounted onto _multiple_ drive slots.

**Comment by frachel** [comment]
@tschak909 Any chance you can take a look at what I've done so far and see if I'm on the right track (since this is a teach-myself learning exercise at this point)? I put a few questions as comments in the code.. (is this type of Q better here or in discord? (this is Schadret in Disc btw)

**Comment by tschak909** [comment]
I definitely think so! Thank you for hacking on this!

**Comment by frachel** [comment]
I've been working on this and come across some things that make make it not-always-accurate and am looking for opinions..

The config program only has 35 characters of a filename, but in the fnconfig.ini/fujinet (where it matters) it has the full filename. 

With deep paths on SD cards or TNFS servers you end up with something like this:

Actual mounted image: `/ATARI/networking/CHATARI-0.8-IRC-Client.atr`
Image name the config program has (current version): `/ATARI/networking/CHATARI-0.8-IRC-C`

You can see this here:

![image](https://user-images.githubusercontent.com/13770228/166080149-466e1d94-95ad-4bbd-8085-5d246450d4cc.png)

The `lient.atr` end-part of the filename has been truncated. If this file were another directory or two deep, the config program wouldn't even have the image name itself, just the 1st 35 chars of the path.

Let's look at this scenario - we mount this image:

![image](https://user-images.githubusercontent.com/13770228/166080305-c42cb66b-c54a-4317-b055-3ffc7431ed5a.png)

On this screen we know the path  `/ATARI/networking/` and the filename `CHATARI-0.8-IRC-Client.atr`. In the structure returned by the SIO call to fill the device slots, it has `/ATARI/networking/CHATARI-0.8-IRC-C`

The dilemma is determining that "yes, we have that image mounted" - what can be compared to answer that question accurately? 

The "full path" of the image is `/ATARI/networking/CHATARI-0.8-IRC-Client.atr` but that will fail a compare against `/ATARI/networking/CHATARI-0.8-IRC-C`. 

We can just compare the first 35 characters, but what if there was a file on the server `/ATARI/networking/CHATARI-0.8-IRC-Client-test.atr` ? Those would both match.. but both are not mounted..

I was thinking of modifying the SIO call so it returns the rightmost characters of the filename - that would make the compare more accurate - but it's ugly displaying it that way (similar to the current display which truncates the right, this way strips the left but matches better):

![image](https://user-images.githubusercontent.com/13770228/166080698-c9731b86-ed4b-4a6a-a791-cbdf83c398ab.png)

So lastly I thought - why not just return the image name with no path:

![image](https://user-images.githubusercontent.com/13770228/166080816-4e21968c-b6e7-49c2-97d5-87fee165ad6e.png)

That seems more user-friendly in the display.. but in this case if you have an image with the same filename (either on the same host but different directories, or on different hosts) those will match and it will think you have it mounted.

Keep in mind this isn't "functionality" - it's just display (this issue is to show you while browsing a host that you already have one of the images you're browsing mounted). But without modifying the underlying SIO call to return more info (ie, return the fill path/filename rather than 36 characters) I don't think there's one way that is going to be 100% accurate..

Hope that made sense.. any thoughts?

I don't think there's a way to 100% match that an image on a host is one you have mounted without having the SIO call return more info - @tschak909 is that type of modification something that can/should be done? I'm unfamiliar with that side of things currently so don't know of changing the buffer from 304 bytes to something larger to accommodate a new field like 'fullFilename' is "easily" doable or not?

Let me know your thoughts here or on Discord (@Schadret)

**Comment by mozzwald** [comment]
This repo is being archived, closing all issues. If issue is still present in current firmware, please open a new issue in the new repo https://github.com/FujiNetWIFI/fujinet-config
